#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if command -v update-mime-database >/dev/null 2>&1; then
            update-mime-database /usr/share/mime || true
        fi

        if [ -d /usr/share/icons/hicolor ]; then
            gtk-update-icon-cache -q /usr/share/icons/hicolor || true
        fi

        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q || true
        fi
    ;;
esac

exit 0

