#!/bin/sh
set -e

# icon cache
if [ -d /usr/share/icons/hicolor ]; then
    gtk-update-icon-cache -q /usr/share/icons/hicolor || true
fi

# desktop database
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q || true
fi

# mime database
if command -v update-mime-database >/dev/null 2>&1; then
    update-mime-database /usr/share/mime || true
fi

exit 0

